[package]
name = "gazania-app"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[[bin]]
name = "gazania-app"
path = "src/main.rs"

[dependencies]
gazania-core.workspace = true
gtk.workspace = true
adw.workspace = true
toml.workspace = true
futures-lite.workspace = true

[build-dependencies]
glib-build-tools.workspace = true
