[package]
name = "zinnia-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
zbus.workspace = true
zvariant.workspace = true
rustix.workspace = true
futures-lite.workspace = true

[dev-dependencies]
tempfile.workspace = true
